### ISSUE TITLE
Door to final boss in Pyramid would not open.

### ISSUE THREAD

**Issue by drkmethos** [Jarno458/TsRandomizer#102]
Seed # 68FC343300004000

I had the timespinner wheel, spindle, and all three gears and had broken time, but the final door wouldn't open. I tried disabling and re-enabling them in the relics menu, didn't work. Exited and re-loaded game, still locked out. (for the heck of it, I tried going back to the timespinner in the lab to see if I could fight the other boss and break time again, but that crashed the game)

I should also note, although this seed only had the "tournament" option enabled, I had early access to the pyramid. I've had 2-3 seeds like that recently, but this was the first I've those that I'd reached the end.

**Comment by Jarno458** [comment]
The flags Tourmanent and Enter Sandman and Fast pyramid where not getting properly set, this should have been resolved in v1.19.2
