### ISSUE TITLE
Feature request: Option to show breakable walls

### ISSUE THREAD

**Issue by mint-cookie** [Jarno458/TsRandomizer#111]
This feature would provide an option to make it so that breakable walls always have the visual indicator as if the oculus ring were equipped. This could be useful for players who have a difficult time remembering the locations of breakable walls, but don't want to have to use the button on the map that shows available checks. I'd make the PR myself, but I wasn't able to figure out where to add it based on reading the existing code.

**Comment by Jarno458** [comment]
i looked into this briefly before, it wasnt so simpel to trigger the effect that, certainly posable but not super easy
