### ISSUE TITLE
Feature: Quick-fill seed flags

### ISSUE THREAD

**Issue by FelicitusNeko** [Jarno458/TsRandomizer#129]
I'd like to suggest something for rolling new seeds with specific flags:
 - Input the flag string (say 1CBF89 for the current tournament's flags)
 - Hit "New"
 - A new seed is generated with the flags represented by the flag string (1234[...]1CBF89)

If the flag string is too short (I'm not sure if it's six or eight chars), front-fill with zeroes (so it would become 001CBF89 if it needs to be eight chars).

**Comment by Jarno458** [comment]
This works if you prefix it with 000000's yourself

**Comment by Jarno458** [comment]
This feature will be added in the next update
