### ISSUE TITLE
Refugee camp portal not working

### ISSUE THREAD

**Issue by ZezaReignhalt** [Jarno458/TsRandomizer#130]
[InternalScreamin.zip](https://github.com/Jarno458/TsRandomizer/files/12842519/InternalScreamin.zip)

So had a current issue with the Randomizer group im running with.

Attached is the current settings but the  Refugee camp warp point is not currently working even though by default it should be working from future to past.

Had to unlock the twin keys in order to progress.  and Due to the nature of the randomizer we had a infinite loop of locks that required me to go to the future and I could not.

**Comment by wafflesoup** [comment]
This yaml was Inverted so the only way to the Present is by getting the Twin Pyramid Key. 

In the next update to Archipelago there will be a new PresentAccessWithWheelAndSpindle option that allows you to go to Present once you have both Wheel and Spindle, but that isn't in Archipelago yet. There is an .apworld available with that feature in the Archipelago discord though.
