### ISSUE TITLE
Feature Request: Personal options for cosmetics

### ISSUE THREAD

**Issue by fluxxdog** [Jarno458/TsRandomizer#63]
When picking up the brooches, it'd be nice if a player could set options for their game to disable their use. For example, If you disable the Eternal Brooch, Lunais's appearance doesn't change when she gets it. This shouldn't be a flag or affect the item pool, but simply be configurable per player.

As this is purely cosmetic in nature, I understand if it's a low priority.

**Comment by JarnoWesthof** [comment]
Plans are to add sprite selection, that should allow people to set the same sprite for the brooch sprites

**Comment by Jarno458** [comment]
This should be resolved in #119
