### ISSUE TITLE
Tablet locked behind being able to read screens with the tablet..?

### ISSUE THREAD

**Issue by IanLuminus** [Jarno458/TsRandomizer#96]
As the title says.
Seed: 77ABF1C30000108F
Timespinner version: v1.033
TsRandomizer version: v0.1.8.1

Library Library: V terminal 1 (War of the Sisters) [Tablet]
Makes it impossible to get..
The lab Lab: Left terminal (Biotechnology) [Succubus Hairpin -> Lightwall -> Celestial Sash]

**Comment by Jarno458** [comment]
That is working as intended, items can be locked behind thier own requirements if they are not mandatory. in this seed you likely had access to the lightwall to finish the seed. and therefor Celestial Sash was not mandatory to finish the game
