### ISSUE TITLE
[Archipelago] Yas queen chest contains plasma orb

### ISSUE THREAD

**Issue by chesslogic** [Jarno458/TsRandomizer#97]
Archipelago Seed: [mZB20dsVTo-Vny-lUI9pCQ](https://archipelago.gg/seed/mZB20dsVTo-Vny-lUI9pCQ)

I had accessibility set to Locations, so I would expect to be able to access the plasma orb in order to open the door to this room.

Maybe you can open the Yas queen room using the plasma spell? Where I was at, we didn't have the spell and the plasma orb was inside the room that needs the plasma orb.

This is a multiworld seed with Accessibility: Locations. Nothing in the room was blocking the run, but I didn't set accessibility to Minimal, so maybe this room needs logic.

**Comment by Jarno458** [comment]
The door can be opened when you have either the orb, spell or ring enquiped. so Plasma Orb, Plasma Gayser or Royal Ring
you likely had access to atleast one of those
Either way if there is an issue here it would be at the Archipelago side not something i can fix so am going to close this
